artifacts:
  base-directory: frontend/build
  discard-paths: 'no'
  files:
  - '**/*'
cache:
  paths:
  - frontend/node_modules/**/*
phases:
  build:
    commands:
    - cd frontend && npm run build && cd ..
  install:
    commands:
    - cd frontend && npm install && cd ..
    runtime-versions:
      nodejs: '14'
  post_build:
    commands:
    - echo Build completed successfully.
  pre_build:
    commands:
    - cd frontend && npm test && cd ..
version: '0.2'
