artifacts:
  base-directory: front-end-react/build
  discard-paths: 'no'
  files:
  - '**/*'
phases:
  build:
    commands:
    - cd front-end-react && npm run build && cd ..
  install:
    commands:
    - cd front-end-react && npm install && cd ..
    runtime-versions:
      nodejs: '16'
  post_build:
    commands:
    - echo Build completed successfully.
  pre_build:
    commands:
    - cd front-end-react && npm test && cd ..
version: '0.2'
 
